### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by networkfusion** [manfriedn64/Controller-Pak-Manager#1]
Hi,

Nice work...

I am wondering what license you use so that I can use some of your source for 240p suite (fonts mainly) and the ED64/Altra64 menu (integrated controller pak manager)...

I could just include the ROM for the latter, so no biggie, but just didn't want to annoy you with using something without accrediting you...

Cheers.

**Comment by matthieularere-msq** [comment]
Hi,

Thanks.

You can use it freely, there is no license of any kind. Feel free to credit me by a link to this repo in some readme file, or don't if you don't have such file. It's not a big deal, I made this for fun ^^

If you improve the fonts, please publish the source. 

Cheers.

**Comment by manfriedn64** [comment]
Hi,

Thanks.

You can use it freely, there is no license of any kind. Feel free to credit me by a link to this repo in some readme file, or don't if you don't have such file. It's not a big deal, I made this for fun ^^

If you improve the fonts, please publish the source.

Cheers.

**Comment by networkfusion** [comment]
Thanks. I would suggest adding a License.md to the root with Unlicense or MIT, but will leave that up to you...

Will feedback anything that may benefit.

Cheers.
